spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://83.8.47.186:3306/to_do?useSSL=false&serverTimezone=UTC
    username: bestuser
    password: bestuser
